set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
add_link_options(-nostdlib)
set(CMAKE_C_COMPILER /usr/bin/arm-none-eabi-gcc)

set(CMAKE_FIND_ROOT_PATH /usr/bin/)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

